---
title: "full_analysis"
author: "Sarah Hvid Andersen"
date: "17/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               lme4,
               stats,
               plyr)
```


```{r}
df_frozen <- read_csv("abm_frozen.csv")
df_frozen_100 <- read_csv("abm_reps.csv")
df_frozen_2 <- read_csv("abm_2reps.csv")

folkeskolen <- read.csv("folkeskolen_stats.csv")

df_frozen <- df_frozen %>% mutate(Version = as.factor(Version),
                    NumberOfStudents = as.factor(NumberOfStudents),
                    Ticks = as.factor(Ticks),
                    ID = as.factor(ID))

```


```{r}

folkeskolen_pr <- folkeskolen %>% select(year, under2_pr, two_four_pr, four_seven_pr, over10_pr)

folkeskolen_pr_18 <- folkeskolen_pr %>% filter(year == "18/19")

folkeskolen_pr_18_long <- folkeskolen_pr_18 %>% gather(value = year)

hist(folkeskolen_pr_18_long$year)
```


```{r}

a <- df_frozen %>%
  group_by(NumberOfStudents) %>%
  dplyr::summarise(across(.cols = Knowledge_percent, list(mean = mean, sd = sd))) 

a

cv_function <- function(n) {
  cv = sd(n) / mean(n)
  
  return(cv)
}

cv_function(df_frozen$Knowledge_percent)
cv_function(df_frozen_100$Knowledge_percent)
cv_function(df_frozen_2$Knowledge_percent)



df_frozen_5 <- df_frozen %>% filter(NumberOfStudents == "5")
df_reps_5 <- df_frozen_100 %>% filter(NumberOfStudents == "5")
df_reps_2 <- df_frozen_2 %>% filter(NumberOfStudents == "5")

cv_function(df_frozen_5$Knowledge_percent)
cv_function(df_reps_5$Knowledge_percent)
cv_function(df_reps_2$Knowledge_percent)


cv1 <-  cv_function(df_frozen_100$Knowledge_percent)

df_frozen$cv <- apply(df_frozen, 1 cv_function(df_frozen$Knowledge_percent))

k <-df_frozen %>% 
  dplyr::rowwise() %>% 
  mutate(CV = cv_function(df_frozen$Knowledge_percent))



```


