---
title: "clean_data"
author: "Sarah Hvid Andersen"
date: "13/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, 
               fs, 
               purrr)

```


the data is in the folder students_output. we need to read in the data from each csv file within. 

```{r}

read_data <- function(filename) {
    # getting filenames and subsetting the relevant parts
    files = path_file(path = filename) 
    
    for (file in filename){
    Date = substr(files, 7, 16)
    Version = substr(files, 18, 30)
    }
    
    # creating dataframes, loading data and merging the df's
    df = data_frame(Date, Version)
    df1 = read.csv(filename)
    data = merge(df, df1)
    
    #depending on how many files we want in the same df, we need to make the ID's unique
    data$id <- paste0(data$Version, data$ID)
    
    # cleaning the variables
    data = data %>% mutate(
        id = as.factor(id),
        NumberOfStudents = as.factor(NumberOfStudents)
        )
    
    
    return(data)
}

# testing on one file
test_data = read_data("Students_output/output2021-05-13_171337-0.csv")
    #it works

# now we can apply it to the files we want to collect into one datafram
df_1 <- list.files(path = 'data_abm_output/students_output_subhyp/', pattern = '.csv', all.files = T, full.names = T) %>% 
    purrr::map_df(read_data)

#correcting ID now that it is one big df
  # there should always be as many Id's as observations in the dataframe
df <- df_1 %>%
  select(-ID) %>% 
  dplyr::rename(ID = id) %>% 
  mutate(
  ID = as.numeric(ID)) %>% 
  mutate(
  ID = as.factor(ID))

  #Knowledge pr tick (grades used for hypothesis 2)
df$Knowledge_Tick <-  df$End_knowledge / df$Ticks

#Maximum attained knowledge = 12 we set to 10200(as you can be better than 12, but you cant be worse than -3) It is also more than 2 sd away from the mean (can be argumented to be outliers)
max_kt <- 0.8878 #max(mv_df$Knowledge_Tick)

    #mean(mv_df_grade$Knowledge_Tick) + 2 * sd(mv_df_grade$Knowledge_Tick)

#Minimum attained knowledge = -3, we set to 2000, to keep the same scale in all (more than 3sd away - the minimum amount of knowledge)
min_kt <- 0.1748042 #min(mv_df$Knowledge_Tick)

    #(mean(mv_df_grade$End_knowledge) + 3 * sd(mv_df_grade$End_knowledge)) - 1322.5

#Finding difference
diffkt <- max_kt-min_kt

#Difference divided by 1500 should give us what 0.01 increment in 7-step grade should be
inckt <- diffkt/1500

#Making a grade for each student based on their end_knowledge 
  #If larger than 12, give 12
df <- df %>% dplyr::rowwise() %>% 
  mutate(Grade_kt = round((((Knowledge_Tick-min_kt)/inckt)-300)/100, 2)) %>% mutate(Grade_kt = ifelse(Grade_kt > 12, 12, Grade_kt)) %>% mutate(Grade_kt = ifelse(Grade_kt < -3, -3, Grade_kt))


# save the full dataset as a csv file to the correct folder
write.csv(df, "data_csv/abm_subhyp.csv")


```

