---
title: "Hypothesis Analysis"
author: "Martine Lind Jensen"
date: "18/5/2021"
output: html_document
---
Analysing the first hypothesis, can we replicate the grades from the danish elementary schools

We have taken numbers to distributed our class size to the model. FROM THE PDF

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse)

```


```{r}
#Reading data 
abm_rep <- read_csv("abm_verfication2.csv")

abm_rep <- abm_rep %>% mutate(Knowledge_percent = End_knowledge/11000)#Maximum amount of knowledge

stats <- read_csv("folkeskolen_stats.csv")
```

Plots

```{r}
#Very nice, looks like we are on to something
abm_frozen %>% ggplot(aes(x = NumberOfStudents, y = Knowledge_percent, fill = NumberOfStudents)) +
  geom_bar(stat = "summary", fun.y = mean)+
  geom_errorbar(stat = "summary", fun.data = mean_se)

abm_frozen %>%ggplot(aes(x = Baseline.attention, y = Version)) + geom_point(aes(color = Version))
abm_frozen %>% ggplot(aes(x = Baseline.attention)) + geom_histogram() + facet_wrap(.~ Version)

#95% problem fixed 
abm_rep %>% ggplot(aes(x = Baseline.attention))+
  geom_histogram(bins = 100) + 
  ggtitle("Distribution of baseline attention values") + 
  xlab("Baseline attention")+ 
  ylab("Count")


#Boxplot
abm_frozen %>% ggplot(aes(x = Baseline.attention ))+ 
  geom_boxplot()


#Plotting knowledge percent as a function of attainment over class size
abm_rep %>% ggplot(aes(x = NumberOfStudents, y = Knowledge_percent, color = ID))+
  stat_summary()+
  geom_smooth(method = "loess") +
  theme(legend.position = "None")

abm_frozen %>% ggplot(aes(x = NumberOfStudents, y = Knowledge_percent))+ 
  geom_point()

#Plotting knowledge percent total 
abm_rep %>% ggplot(aes(x = Knowledge_percent))+
  stat_bin(bins = 7)+
  stat_bin(bins= 7, geom="text", aes(label=round((..count..)/sum(..count..)*100, 2))) +
  scale_y_continuous(labels = scales::percent_format()) + 
  ggtitle("Grade distribution from knowledge percent")
  #This follows the distribution of how to give grades almost perfectly 

abm_rep %>% ggplot(aes(x = Knowledge_percent))+
  stat_bin(bins = 100)+
  stat_bin(bins= 100, geom="text", aes(label=round((..count..)/sum(..count..)*100, 2))) +
  scale_y_continuous(labels = scales::percent_format()) + 
  ggtitle("Grade distribution from knowledge percent")

abm_rep %>% ggplot(aes(x = End_knowledge))+
  stat_bin(bins = 50)+
  stat_bin(bins= 50, geom="text", aes(label=round((..count..)/sum(..count..)*100, 2))) +
  scale_y_continuous(labels = scales::percent_format()) + 
  ggtitle("Grade distribution from knowledge percent")

#Plotting knowledge percent by number of students 
abm_rep %>% ggplot(aes(x = Knowledge_percent)) +
  stat_bin(bins = 50) +
  stat_bin(bins = 50, geom = "text", aes(label = round((..count..)/sum(..count..)*100,2)), size=3) +
  facet_wrap(.~NumberOfStudents)
```

Can we replicate the Danish school system 
```{r}
#Finding percentile from undervisningsministeriets definition of grades
q <-data.frame(quantile(abm_rep$Knowledge_percent, c(.10, .35, .65, .9))) #10 lowest 0.2 or under, next 25% 4, next 30% 7, next 25% 10, last 10% 12. 

#Giving knowledge percent grades 
abm_rep_grades <- abm_rep %>% dplyr::rowwise() %>% 
  mutate(Grade = 
           ifelse(Knowledge_percent > 0.8413455, runif(1, 10, 12),
                  ifelse(Knowledge_percent < 0.8413455 & Knowledge_percent > 0.7459136, runif(1, 7, 10),
                         ifelse(Knowledge_percent < 0.7459136 & Knowledge_percent > 0.6501364, runif(1, 4, 7),
                                ifelse(Knowledge_percent < 0.6501364 & Knowledge_percent > 0.5281091, runif(1, 2, 4),
                                       ifelse(Knowledge_percent < 0.5281091, runif(1, 0, 2), "no"))))))
```


```{r}
#Scaling to the distribution 
    #This means that we have a 100% / 15 (15 because we have from -3 to 12, there is 15 hole numbers). Then the increment is from -3 to 0 = 3, 0 to 2 = 2 and so on. 100/15 = 6.7 multiplied with the numbers of increment gives these numbers ->
abm_rep_grades <- abm_rep %>% 
  mutate(Grade = 
           ifelse(Knowledge_percent > 0.8413455, 12,
                  ifelse(Knowledge_percent < 0.8413455 & Knowledge_percent > 0.7459136, 10,
                         ifelse(Knowledge_percent < 0.7459136 & Knowledge_percent > 0.6501364, 7,
                                ifelse(Knowledge_percent < 0.6501364 & Knowledge_percent > 0.5281091, 4,
                                       ifelse(Knowledge_percent < 0.5281091, 02, "no"))))))

#Plotting
abm_rep_grades %>% ggplot(aes(x = Grade)) +
  geom_bar(aes(x = Grade, y = (..count..)/sum(..count..)*100)) + 
  ggtitle("Distribution of grades") +
  xlab("Grades") +
  ylab("Percent")
```


```{r}
abm_frozen %>% group_by(NumberOfStudents) %>% dplyr::count(Grade == "7-10")
  stat_bin(bins = 5) +
  stat_bin(bins = 5, geom = "text", aes(label = round((..count..)/sum(..count..)*100,2)), size=3) #+
  facet_wrap(.~NumberOfStudents)


mean(abm_frozen_grades$Grade)
mean(abm_frozen_grades$Knowledge_percent)

x <- seq(0, 100, by= .1)
y <- dnorm(x, mean = 10, sd = 7)
#y <- dlnorm(x, meanlog = 0.18, sdlog = 0.9)
df <- data.frame(x,y)
ggplot(df, aes(x,y))+ 
  geom_line()

```

